// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf_valid.proto
package example;

public final class ProtobufValidOuterClass {
  private ProtobufValidOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProtobufValidOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProtobufValid)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 example_int32 = 1;</code>
     */
    int getExampleInt32();

    /**
     * <code>optional int64 example_int64 = 2;</code>
     */
    long getExampleInt64();

    /**
     * <code>optional uint32 example_uint32 = 3;</code>
     */
    int getExampleUint32();

    /**
     * <code>optional uint64 example_uint64 = 4;</code>
     */
    long getExampleUint64();

    /**
     * <code>optional sint32 example_sint32 = 5;</code>
     */
    int getExampleSint32();

    /**
     * <code>optional sint64 example_sint64 = 6;</code>
     */
    long getExampleSint64();

    /**
     * <code>optional bool example_bool = 7;</code>
     */
    boolean getExampleBool();
  }
  /**
   * Protobuf type {@code ProtobufValid}
   */
  public  static final class ProtobufValid extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ProtobufValid)
      ProtobufValidOrBuilder {
    // Use ProtobufValid.newBuilder() to construct.
    private ProtobufValid(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProtobufValid() {
      exampleInt32_ = 0;
      exampleInt64_ = 0L;
      exampleUint32_ = 0;
      exampleUint64_ = 0L;
      exampleSint32_ = 0;
      exampleSint64_ = 0L;
      exampleBool_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ProtobufValid(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              exampleInt32_ = input.readInt32();
              break;
            }
            case 16: {

              exampleInt64_ = input.readInt64();
              break;
            }
            case 24: {

              exampleUint32_ = input.readUInt32();
              break;
            }
            case 32: {

              exampleUint64_ = input.readUInt64();
              break;
            }
            case 40: {

              exampleSint32_ = input.readSInt32();
              break;
            }
            case 48: {

              exampleSint64_ = input.readSInt64();
              break;
            }
            case 56: {

              exampleBool_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtobufValidOuterClass.internal_static_ProtobufValid_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtobufValidOuterClass.internal_static_ProtobufValid_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtobufValidOuterClass.ProtobufValid.class, ProtobufValidOuterClass.ProtobufValid.Builder.class);
    }

    public static final int EXAMPLE_INT32_FIELD_NUMBER = 1;
    private int exampleInt32_;
    /**
     * <code>optional int32 example_int32 = 1;</code>
     */
    public int getExampleInt32() {
      return exampleInt32_;
    }

    public static final int EXAMPLE_INT64_FIELD_NUMBER = 2;
    private long exampleInt64_;
    /**
     * <code>optional int64 example_int64 = 2;</code>
     */
    public long getExampleInt64() {
      return exampleInt64_;
    }

    public static final int EXAMPLE_UINT32_FIELD_NUMBER = 3;
    private int exampleUint32_;
    /**
     * <code>optional uint32 example_uint32 = 3;</code>
     */
    public int getExampleUint32() {
      return exampleUint32_;
    }

    public static final int EXAMPLE_UINT64_FIELD_NUMBER = 4;
    private long exampleUint64_;
    /**
     * <code>optional uint64 example_uint64 = 4;</code>
     */
    public long getExampleUint64() {
      return exampleUint64_;
    }

    public static final int EXAMPLE_SINT32_FIELD_NUMBER = 5;
    private int exampleSint32_;
    /**
     * <code>optional sint32 example_sint32 = 5;</code>
     */
    public int getExampleSint32() {
      return exampleSint32_;
    }

    public static final int EXAMPLE_SINT64_FIELD_NUMBER = 6;
    private long exampleSint64_;
    /**
     * <code>optional sint64 example_sint64 = 6;</code>
     */
    public long getExampleSint64() {
      return exampleSint64_;
    }

    public static final int EXAMPLE_BOOL_FIELD_NUMBER = 7;
    private boolean exampleBool_;
    /**
     * <code>optional bool example_bool = 7;</code>
     */
    public boolean getExampleBool() {
      return exampleBool_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (exampleInt32_ != 0) {
        output.writeInt32(1, exampleInt32_);
      }
      if (exampleInt64_ != 0L) {
        output.writeInt64(2, exampleInt64_);
      }
      if (exampleUint32_ != 0) {
        output.writeUInt32(3, exampleUint32_);
      }
      if (exampleUint64_ != 0L) {
        output.writeUInt64(4, exampleUint64_);
      }
      if (exampleSint32_ != 0) {
        output.writeSInt32(5, exampleSint32_);
      }
      if (exampleSint64_ != 0L) {
        output.writeSInt64(6, exampleSint64_);
      }
      if (exampleBool_ != false) {
        output.writeBool(7, exampleBool_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (exampleInt32_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, exampleInt32_);
      }
      if (exampleInt64_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, exampleInt64_);
      }
      if (exampleUint32_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, exampleUint32_);
      }
      if (exampleUint64_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, exampleUint64_);
      }
      if (exampleSint32_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(5, exampleSint32_);
      }
      if (exampleSint64_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(6, exampleSint64_);
      }
      if (exampleBool_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, exampleBool_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ProtobufValidOuterClass.ProtobufValid)) {
        return super.equals(obj);
      }
      ProtobufValidOuterClass.ProtobufValid other = (ProtobufValidOuterClass.ProtobufValid) obj;

      boolean result = true;
      result = result && (getExampleInt32()
          == other.getExampleInt32());
      result = result && (getExampleInt64()
          == other.getExampleInt64());
      result = result && (getExampleUint32()
          == other.getExampleUint32());
      result = result && (getExampleUint64()
          == other.getExampleUint64());
      result = result && (getExampleSint32()
          == other.getExampleSint32());
      result = result && (getExampleSint64()
          == other.getExampleSint64());
      result = result && (getExampleBool()
          == other.getExampleBool());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + EXAMPLE_INT32_FIELD_NUMBER;
      hash = (53 * hash) + getExampleInt32();
      hash = (37 * hash) + EXAMPLE_INT64_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getExampleInt64());
      hash = (37 * hash) + EXAMPLE_UINT32_FIELD_NUMBER;
      hash = (53 * hash) + getExampleUint32();
      hash = (37 * hash) + EXAMPLE_UINT64_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getExampleUint64());
      hash = (37 * hash) + EXAMPLE_SINT32_FIELD_NUMBER;
      hash = (53 * hash) + getExampleSint32();
      hash = (37 * hash) + EXAMPLE_SINT64_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getExampleSint64());
      hash = (37 * hash) + EXAMPLE_BOOL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getExampleBool());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ProtobufValidOuterClass.ProtobufValid parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtobufValidOuterClass.ProtobufValid parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtobufValidOuterClass.ProtobufValid parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtobufValidOuterClass.ProtobufValid parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtobufValidOuterClass.ProtobufValid parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtobufValidOuterClass.ProtobufValid parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtobufValidOuterClass.ProtobufValid parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ProtobufValidOuterClass.ProtobufValid parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtobufValidOuterClass.ProtobufValid parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtobufValidOuterClass.ProtobufValid parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ProtobufValidOuterClass.ProtobufValid prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProtobufValid}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProtobufValid)
        ProtobufValidOuterClass.ProtobufValidOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtobufValidOuterClass.internal_static_ProtobufValid_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtobufValidOuterClass.internal_static_ProtobufValid_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtobufValidOuterClass.ProtobufValid.class, ProtobufValidOuterClass.ProtobufValid.Builder.class);
      }

      // Construct using ProtobufValidOuterClass.ProtobufValid.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        exampleInt32_ = 0;

        exampleInt64_ = 0L;

        exampleUint32_ = 0;

        exampleUint64_ = 0L;

        exampleSint32_ = 0;

        exampleSint64_ = 0L;

        exampleBool_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtobufValidOuterClass.internal_static_ProtobufValid_descriptor;
      }

      public ProtobufValidOuterClass.ProtobufValid getDefaultInstanceForType() {
        return ProtobufValidOuterClass.ProtobufValid.getDefaultInstance();
      }

      public ProtobufValidOuterClass.ProtobufValid build() {
        ProtobufValidOuterClass.ProtobufValid result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ProtobufValidOuterClass.ProtobufValid buildPartial() {
        ProtobufValidOuterClass.ProtobufValid result = new ProtobufValidOuterClass.ProtobufValid(this);
        result.exampleInt32_ = exampleInt32_;
        result.exampleInt64_ = exampleInt64_;
        result.exampleUint32_ = exampleUint32_;
        result.exampleUint64_ = exampleUint64_;
        result.exampleSint32_ = exampleSint32_;
        result.exampleSint64_ = exampleSint64_;
        result.exampleBool_ = exampleBool_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtobufValidOuterClass.ProtobufValid) {
          return mergeFrom((ProtobufValidOuterClass.ProtobufValid)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtobufValidOuterClass.ProtobufValid other) {
        if (other == ProtobufValidOuterClass.ProtobufValid.getDefaultInstance()) return this;
        if (other.getExampleInt32() != 0) {
          setExampleInt32(other.getExampleInt32());
        }
        if (other.getExampleInt64() != 0L) {
          setExampleInt64(other.getExampleInt64());
        }
        if (other.getExampleUint32() != 0) {
          setExampleUint32(other.getExampleUint32());
        }
        if (other.getExampleUint64() != 0L) {
          setExampleUint64(other.getExampleUint64());
        }
        if (other.getExampleSint32() != 0) {
          setExampleSint32(other.getExampleSint32());
        }
        if (other.getExampleSint64() != 0L) {
          setExampleSint64(other.getExampleSint64());
        }
        if (other.getExampleBool() != false) {
          setExampleBool(other.getExampleBool());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtobufValidOuterClass.ProtobufValid parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtobufValidOuterClass.ProtobufValid) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int exampleInt32_ ;
      /**
       * <code>optional int32 example_int32 = 1;</code>
       */
      public int getExampleInt32() {
        return exampleInt32_;
      }
      /**
       * <code>optional int32 example_int32 = 1;</code>
       */
      public Builder setExampleInt32(int value) {
        
        exampleInt32_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 example_int32 = 1;</code>
       */
      public Builder clearExampleInt32() {
        
        exampleInt32_ = 0;
        onChanged();
        return this;
      }

      private long exampleInt64_ ;
      /**
       * <code>optional int64 example_int64 = 2;</code>
       */
      public long getExampleInt64() {
        return exampleInt64_;
      }
      /**
       * <code>optional int64 example_int64 = 2;</code>
       */
      public Builder setExampleInt64(long value) {
        
        exampleInt64_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 example_int64 = 2;</code>
       */
      public Builder clearExampleInt64() {
        
        exampleInt64_ = 0L;
        onChanged();
        return this;
      }

      private int exampleUint32_ ;
      /**
       * <code>optional uint32 example_uint32 = 3;</code>
       */
      public int getExampleUint32() {
        return exampleUint32_;
      }
      /**
       * <code>optional uint32 example_uint32 = 3;</code>
       */
      public Builder setExampleUint32(int value) {
        
        exampleUint32_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 example_uint32 = 3;</code>
       */
      public Builder clearExampleUint32() {
        
        exampleUint32_ = 0;
        onChanged();
        return this;
      }

      private long exampleUint64_ ;
      /**
       * <code>optional uint64 example_uint64 = 4;</code>
       */
      public long getExampleUint64() {
        return exampleUint64_;
      }
      /**
       * <code>optional uint64 example_uint64 = 4;</code>
       */
      public Builder setExampleUint64(long value) {
        
        exampleUint64_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 example_uint64 = 4;</code>
       */
      public Builder clearExampleUint64() {
        
        exampleUint64_ = 0L;
        onChanged();
        return this;
      }

      private int exampleSint32_ ;
      /**
       * <code>optional sint32 example_sint32 = 5;</code>
       */
      public int getExampleSint32() {
        return exampleSint32_;
      }
      /**
       * <code>optional sint32 example_sint32 = 5;</code>
       */
      public Builder setExampleSint32(int value) {
        
        exampleSint32_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 example_sint32 = 5;</code>
       */
      public Builder clearExampleSint32() {
        
        exampleSint32_ = 0;
        onChanged();
        return this;
      }

      private long exampleSint64_ ;
      /**
       * <code>optional sint64 example_sint64 = 6;</code>
       */
      public long getExampleSint64() {
        return exampleSint64_;
      }
      /**
       * <code>optional sint64 example_sint64 = 6;</code>
       */
      public Builder setExampleSint64(long value) {
        
        exampleSint64_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint64 example_sint64 = 6;</code>
       */
      public Builder clearExampleSint64() {
        
        exampleSint64_ = 0L;
        onChanged();
        return this;
      }

      private boolean exampleBool_ ;
      /**
       * <code>optional bool example_bool = 7;</code>
       */
      public boolean getExampleBool() {
        return exampleBool_;
      }
      /**
       * <code>optional bool example_bool = 7;</code>
       */
      public Builder setExampleBool(boolean value) {
        
        exampleBool_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool example_bool = 7;</code>
       */
      public Builder clearExampleBool() {
        
        exampleBool_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ProtobufValid)
    }

    // @@protoc_insertion_point(class_scope:ProtobufValid)
    private static final ProtobufValidOuterClass.ProtobufValid DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ProtobufValidOuterClass.ProtobufValid();
    }

    public static ProtobufValidOuterClass.ProtobufValid getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProtobufValid>
        PARSER = new com.google.protobuf.AbstractParser<ProtobufValid>() {
      public ProtobufValid parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ProtobufValid(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProtobufValid> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProtobufValid> getParserForType() {
      return PARSER;
    }

    public ProtobufValidOuterClass.ProtobufValid getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtobufValid_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProtobufValid_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024protobuf_valid.proto\"\263\001\n\rProtobufValid" +
      "\022\025\n\rexample_int32\030\001 \001(\005\022\025\n\rexample_int64" +
      "\030\002 \001(\003\022\026\n\016example_uint32\030\003 \001(\r\022\026\n\016exampl" +
      "e_uint64\030\004 \001(\004\022\026\n\016example_sint32\030\005 \001(\021\022\026" +
      "\n\016example_sint64\030\006 \001(\022\022\024\n\014example_bool\030\007" +
      " \001(\010b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ProtobufValid_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ProtobufValid_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProtobufValid_descriptor,
        new java.lang.String[] { "ExampleInt32", "ExampleInt64", "ExampleUint32", "ExampleUint64", "ExampleSint32", "ExampleSint64", "ExampleBool", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
